# Example1:
#    - paths:
#      - sketchbook_path: /home/bcmi/Arduino
#      - arduino_data: /home/bcmi/.arduino15
#    - proxy:
#      - type: auto

# https://github.com/arduino/arduino-cli/blob/master/.cli-config_example.yml